apiVersion: v1
kind: Service
metadata:
  name: myapp-service-backup
spec:
  selector:
    app: blue
  ports:
    - protocol: TCP
      port: 81
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - 103.146.224.225
