name: Python CD

on:

  #push:
   # branches: ["workflow_test"]
  #pull_request:
   # branches: ["workflow_test"]

  workflow_dispatch:
    inputs:
      tag:
        description: Docker image tag
        required: true
        default: latest

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
